<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Yaml\Exception\DumpException" namespace="Symfony\Component\Yaml\Exception" name="DumpException" abstract="false" final="false" start="19" end="21">
  <file path="/home/web/example/src/freegame_developer/vendor/symfony/yaml/Exception" file="DumpException.php" realpath="/home/web/example/src/freegame_developer/vendor/symfony/yaml/Exception/DumpException.php" size="455" time="2016-10-24T18:41:13+00:00" unixtime="1477334473" sha1="21476de0db89c3019b229ad02d7637ba72eb93d1" relative="freegame_developer/vendor/symfony/yaml/Exception/DumpException.php"/>
  <docblock>
    <description compact="Exception class thrown when an error occurs during dumping."/>
    <author value="Fabien Potencier &lt;fabien@symfony.com&gt;"/>
  </docblock>
  <extends full="Symfony\Component\Yaml\Exception\RuntimeException" namespace="Symfony\Component\Yaml\Exception" name="RuntimeException"/>
</class>
