<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://xml.phpdox.net/src" full="Symfony\Component\Yaml\Exception\RuntimeException" namespace="Symfony\Component\Yaml\Exception" name="RuntimeException" abstract="false" final="false" start="19" end="21">
  <file path="/home/web/example/src/freegame_developer/vendor/symfony/yaml/Exception" file="RuntimeException.php" realpath="/home/web/example/src/freegame_developer/vendor/symfony/yaml/Exception/RuntimeException.php" size="485" time="2016-10-24T18:41:13+00:00" unixtime="1477334473" sha1="6d51f0c7062aee98ce4dc1077c2c2f2470d734f3" relative="freegame_developer/vendor/symfony/yaml/Exception/RuntimeException.php"/>
  <docblock>
    <description compact="Exception class thrown when an error occurs during parsing."/>
    <author value="Romain Neutron &lt;imprec@gmail.com&gt;"/>
  </docblock>
  <extends full="RuntimeException" namespace="" name="RuntimeException"/>
  <implements full="Symfony\Component\Yaml\Exception\ExceptionInterface" namespace="Symfony\Component\Yaml\Exception" name="ExceptionInterface"/>
</class>
